CREATE TABLE LM_ORGANIZATION(
	ORGANIZATION_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ORGANIZATION_NAME VARCHAR(300) NOT NULL
);

CREATE TABLE LM_REPOSITORY(
	REPOSITORY_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	REPOSITORY_NAME VARCHAR(300) NOT NULL,
	REPOSITORY_LANGUAGE VARCHAR(50),
	REPOSITORY_BUILDABLE BOOLEAN DEFAULT NULL,
	REPOSITORY_PRIVATE BOOLEAN DEFAULT NULL,
	REPOSITORY_DESCRIPTION LONG VARCHAR,
	REPOSITORY_LICENSE INT(11),
	REPOSITORY_GROUPID INTEGER,
	REPOSITORY_ORGANIZATION INTEGER,
	REPOSITORY_TYPE INTEGER,
	REPOSITORY_ACTIVE BOOLEAN DEFAULT NULL,
	REPOSITORY_ACCEPT BOOLEAN DEFAULT NULL,

	FOREIGN KEY (REPOSITORY_LICENSE) REFERENCES LM_LICENSE(LICENSE_ID),
	FOREIGN KEY (REPOSITORY_GROUPID) REFERENCES LM_GROUP(GROUP_ID),
	FOREIGN KEY (REPOSITORY_ORGANIZATION) REFERENCES LM_ORGANIZATION(ORGANIZATION_ID),
	FOREIGN KEY (REPOSITORY_TYPE) REFERENCES LM_REPOSITORYTYPE(REPOSITORYTYPE_ID)
)ENGINE=MyISAM AUTO_INCREMENT=32 DEFAULT CHARSET=latin1;

CREATE TABLE LM_REPOSITORYTYPE(
	REPOSITORYTYPE_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	REPOSITORYTYPE_NAME VARCHAR(300) NOT NULL,
	REPOSITORYTYPE_JENKINS BOOLEAN DEFAULT NULL,
	REPOSITORYTYPE_NEXUS BOOLEAN DEFAULT NULL
);

CREATE TABLE LM_GROUP(
	GROUP_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	GROUP_NAME VARCHAR(100) NOT NULL
);



